### ISSUE TITLE
Замечания на допуск

### ISSUE THREAD

**Issue by juwain** [Moskovka/first#1]
### Базовые критерии
- [x] Б5. Документ проходит проверку на валидность http://validator.w3.org/nu/ . Нужно поправить ошибки.
- [x] Б7. Раскладка блоков на странице сделана не с помощью таблиц или позиционирования.
  Могут придраться к табличке .hotel-info. Лучше там сделать раскладку дивами.
- [x] Б9. Подключены правильные шрифты, их размеры и толщина соответствуют размерам в макетах и ТЗ. 
  Пункты меню должны быть bold.
- [x] Б15. Единообразное написание и форматирование кода в HTML, CSS и JavaScript. Надо всё причесать, отступы гуляют. Нужно везде отформатировать. Может помочь пакет atom-beautify, например.
- [x] Б13. Сайт нормально смотрится на минимальном для макета разрешении. Седона — 768px (для фиксированной можно использовать либо версию 768px, либо 1200px). Из-за левых и правых отступов у .main-navigation a, скролл начинает появляться на 1220px, а должен начинать появляться на 1200px.
### Дополнительные критерии (дополню позже)
- [x] надо уменьшить всё таки исходную картинку main-img.jpg, а то она весит 1мб, нам нужно максимум 1200px разрешение
- [x] вынести иконки icon-flat.png и две другие в спрайт

**Comment by moskovka** [comment]
Б9. — не так то, что "пункты меню должны быть bold"? а если по макету они не bold?

**Comment by moskovka** [comment]
Б13. — я не поняла. я просто удалила отступы и теперь всё ок?

**Comment by moskovka** [comment]
"надо уменьшить всё таки исходную картинку main-img.jpg, а то она весит 1мб, нам нужно максимум 1200px разрешение" — я обрезала снизу картинку, но вроде она всё равно тяжелая..

**Comment by moskovka** [comment]
"вынести иконки icon-flat.png и две другие в спайт" — о нет! там такое больше расстояние надо делать, чтобы другие элементы не было видно.. это все отступы поедут в других спрайтах..

**Comment by juwain** [comment]
> Б9. — не так то, что "пункты меню должны быть bold"? а если по макету они не bold?

![2015-09-23 15 43 28](https://cloud.githubusercontent.com/assets/928081/10045269/17b0666a-620a-11e5-95cf-6ac17867fbfa.png)

А у меня bold

**Comment by juwain** [comment]
> "вынести иконки icon-flat.png и две другие в спайт" — о нет! там такое больше расстояние надо делать, чтобы другие элементы не было видно.. это все отступы поедут в других спрайтах..

Можно их вниз подсунуть, чтобы предыдущие не ломались

**Comment by juwain** [comment]
> Б13. — я не поняла. я просто удалила отступы и теперь всё ок?

Да теперь ок

**Comment by juwain** [comment]
> "надо уменьшить всё таки исходную картинку main-img.jpg, а то она весит 1мб, нам нужно максимум 1200px разрешение" — я обрезала снизу картинку, но вроде она всё равно тяжелая..

можно попробовать в фотошопе разрешение уменьшить до 1200px и save for web затем

**Comment by moskovka** [comment]
Б7. — переверстала дивами, но не знаю как сделать отступ до цены, так чтобы цена всегда ровно было с кнопкой внизу..

**Comment by moskovka** [comment]
"Можно их вниз подсунуть, чтобы предыдущие не ломались" — а можно им задать больше отступы чем остальным? не могу тут найти такое http://spritegen.website-performance.org

**Comment by moskovka** [comment]
"можно попробовать в фотошопе разрешение уменьшить до 1200px и save for web затем" — там ширина картинки всего 1200, только верх и низ можно обрезать получается же

**Comment by juwain** [comment]
> "Можно их вниз подсунуть, чтобы предыдущие не ломались" — а можно им задать больше отступы чем остальным? не могу тут найти такое http://spritegen.website-performance.org

Проще их добавить в спрайт как обычно, просто задавать фоном не самим блокам features-item, а добавить псевдоэлемент features-item и уже ему назначать фон (как иконки в соц. кнопок).

**Comment by juwain** [comment]
> "можно попробовать в фотошопе разрешение уменьшить до 1200px и save for web затем" — там ширина картинки всего 1200, только верх и низ можно обрезать получается же

Нет, она счас же > 2000px

![2015-09-23 16 15 49](https://cloud.githubusercontent.com/assets/928081/10045968/e54bfc5c-620e-11e5-890c-40885ddd0541.png)

**Comment by juwain** [comment]
> Б7. — переверстала дивами, но не знаю как сделать отступ до цены, так чтобы цена всегда ровно было с кнопкой внизу..

Можно блокам задать минимальную ширину, например.

Или же сделать CSS-таблицу. display:table, display: table-cell, вот это всё ))

**Comment by moskovka** [comment]
Б7.  — лучше минимальную ширину =))

**Comment by juwain** [comment]
> Б7. — лучше минимальную ширину =))

ок
